### ISSUE TITLE
possible tag parsing bug

### ISSUE THREAD

**Issue by colinlieberman** [gosukiwi/atom-gutentags#1]
Someone with ctags reckons https://github.com/universal-ctags/ctags/issues/2632 isn't an issue on their side.

@gosukiwi, could you have a look at masatake's comments there and let me know what you think?

Thanks!

**Comment by gosukiwi** [comment]
Weird. I'll try to reproduce it later. All this plugin does is generate the `tags` file though, the actual functionality of navigating to it is in the `symbols-view` package which is part of Atom core.

So maybe we should open an issue over there. But first I'd like to try and reproduce it myself :)

**Comment by gosukiwi** [comment]
Yeah I was able to reproduce your issue on my end, but the tagfile is generated properly, so I think we should move this to https://github.com/atom/symbols-view

**Comment by gosukiwi** [comment]
Moved over there: https://github.com/atom/symbols-view/issues/256
